import type { Metadata } from "next";
import { Inter, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import { TailwindIndicator } from "@/components/TwIndicatior";

const inter = Inter({ subsets: ["latin"] });
const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shareTechMono.className}>
        <div className="flex h-screen bg-black text-red-500">
          <div className="flex-1">{children}</div>
        </div>
        {/* <TailwindIndicator /> */}
      </body>
    </html>
  );
}
